set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(NOT DEFINED ENV{ORIN_SYSROOT})
  message(FATAL_ERROR "ORIN_SYSROOT is not set")
endif()

set(CMAKE_SYSROOT "$ENV{ORIN_SYSROOT}")
set(CMAKE_STAGING_PREFIX "$ENV{ORIN_STAGING_PREFIX}")
if(DEFINED ENV{ORIN_MAKE_PROGRAM})
  set(CMAKE_MAKE_PROGRAM "$ENV{ORIN_MAKE_PROGRAM}" CACHE FILEPATH "Host make program")
else()
  set(CMAKE_MAKE_PROGRAM /usr/bin/make CACHE FILEPATH "Host make program")
endif()

if(DEFINED ENV{ORIN_USE_SYSROOT_TOOLCHAIN} AND "$ENV{ORIN_USE_SYSROOT_TOOLCHAIN}" STREQUAL "1")
  set(CMAKE_PROGRAM_PATH "${CMAKE_SYSROOT}/usr/bin")
  set(CMAKE_C_COMPILER "${CMAKE_SYSROOT}/usr/bin/aarch64-linux-gnu-gcc")
  set(CMAKE_CXX_COMPILER "${CMAKE_SYSROOT}/usr/bin/aarch64-linux-gnu-g++")
  set(CMAKE_AR "${CMAKE_SYSROOT}/usr/bin/aarch64-linux-gnu-ar")
  set(CMAKE_RANLIB "${CMAKE_SYSROOT}/usr/bin/aarch64-linux-gnu-ranlib")
  set(CMAKE_STRIP "${CMAKE_SYSROOT}/usr/bin/aarch64-linux-gnu-strip")
elseif(DEFINED ENV{ORIN_TOOLCHAIN_ROOT})
  set(ORIN_TOOLCHAIN_ROOT "$ENV{ORIN_TOOLCHAIN_ROOT}")
  set(CMAKE_PROGRAM_PATH "${ORIN_TOOLCHAIN_ROOT}/bin")
  set(CMAKE_C_COMPILER "${ORIN_TOOLCHAIN_ROOT}/bin/aarch64-buildroot-linux-gnu-gcc")
  set(CMAKE_CXX_COMPILER "${ORIN_TOOLCHAIN_ROOT}/bin/aarch64-buildroot-linux-gnu-g++")
  set(CMAKE_AR "${ORIN_TOOLCHAIN_ROOT}/bin/aarch64-buildroot-linux-gnu-ar")
  set(CMAKE_RANLIB "${ORIN_TOOLCHAIN_ROOT}/bin/aarch64-buildroot-linux-gnu-ranlib")
  set(CMAKE_STRIP "${ORIN_TOOLCHAIN_ROOT}/bin/aarch64-buildroot-linux-gnu-strip")
else()
  set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
  set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)
endif()

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}" "${CMAKE_STAGING_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_LIBRARY_ARCHITECTURE aarch64-linux-gnu)
set(PKG_CONFIG_EXECUTABLE /usr/bin/pkg-config)
if(DEFINED ENV{ROS_DISTRO_TARGET})
  set(ROS_DISTRO_TARGET "$ENV{ROS_DISTRO_TARGET}")
else()
  set(ROS_DISTRO_TARGET humble)
endif()
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig:${CMAKE_SYSROOT}/opt/ros/${ROS_DISTRO_TARGET}/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/opt/ros/${ROS_DISTRO_TARGET}/lib/pkgconfig")
